language: node_js
node_js:
  - "0.11"
env:
  - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=OkbR2OXNDJmBqkTX5UyauYmaM3aw9s5ym
script:
  - ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
